# Generated by Django 4.0.6 on 2022-07-25 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.TextField(blank=True)),
                ('article_body', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
    ]
